name: notification_handler
description: Handle event notifications and provide state for Flutter app
version: 0.0.1
author: najeira
homepage: https://github.com/najeira/flutter-notification-handler

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
